// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//
// For the legal audit database use a separate schema and migrations directory:
//   npx prisma generate --schema prisma/schema.legal.prisma
//   npx prisma migrate dev \
//     --schema=prisma/schema.legal.prisma \
//     --migrations-dir=prisma/migrations-legal \
//     --name <migration_name>
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
