sonar.organization=pierfreeman
sonar.projectKey=pierfreeman_saas-backend-blueprint

sonar.sources=apps,libs
sonar.exclusions=**/*.spec.ts,**/*.test.ts,**/node_modules/**,**/dist/**,coverage/**,prisma/**,tmp/**
sonar.coverage.exclusions=\
  **/vitest.config.ts,\
  **/vitest.workspace.ts
sonar.cpd.exclusions=\
  **/vitest.config.ts,\
  **/vitest.workspace.ts,\
  **/main.ts

sonar.tests=apps,libs
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts

sonar.javascript.lcov.reportPaths=coverage/unit/**/lcov.info,coverage/integration/**/lcov.info
sonar.typescript.tsconfigPath=tsconfig.base.json
