/**
 * DomainEvent Interface
 * Shared contract for all events in the system.
 * Used for both in-process (local) and distributed (SQS) events.
 */
export interface DomainEvent<
  T extends Record<string, unknown> = Record<string, unknown>,
> {
  /** Event name in dot-notation, e.g. "heavy.job.created" */
  eventType: string;
  /** Timestamp when the event was created */
  timestamp: Date;
  /** Typed event payload */
  payload: T;
  /** Tenant ID (multi-tenancy) */
  tenantId?: string;
  /** ID of the user who originated the event */
  userId?: string;
  /**
   * Unique event ID used for deduplication (required for SQS FIFO).
   * Auto-generated by EventBusService if not provided.
   */
  eventId?: string;
  /**
   * MessageGroupId for SQS FIFO — groups events that must be
   * processed in order (e.g. all events for a given tenant).
   * Defaults to tenantId if present, otherwise 'default'.
   */
  messageGroupId?: string;
}
