FROM node:20.20.1-alpine3.22

WORKDIR /app

COPY package.json package-lock.json ./
COPY prisma ./prisma
COPY prisma.config.ts prisma.config.legal.ts ./

RUN npm ci --ignore-scripts --fetch-retries=5 --fetch-retry-mintimeout=20000 --fetch-retry-maxtimeout=120000 && \
	chown -R node:node /app
USER node

CMD ["npx", "prisma", "migrate", "deploy", "--config", "prisma.config.ts"]
